apps/geovinci/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^$', 'geovinci.views.front.index', name='index'),
    url(r'nearme/', include('nearme.urls', namespace='nearme')),

    url(r'^admin/', include(admin.site.urls)),
] + staticfiles_urlpatterns()

apps/nearme/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'nearme.views.front.index', name='index'),
    url(r'^coarse$', 'nearme.views.api.coarse', name='coarse'),
    url(r'^fine$', 'nearme.views.api.fine', name='fine'),
    url(r'^campuses/$', 'nearme.views.api.campuses', name='campuses'),
]

apps/nearme/models.py
# from django.db import models
from django.contrib.gis.db import models


class CampusLocation(models.Model):
    """
    A general location of the campus
    """
    street_address = models.CharField(max_length=240)
    additional_address = models.CharField(
        max_length=240, blank=True, help_text="Apartment or Suite Number")
    locality = models.CharField(
        help_text="The city or municipality of the campus", max_length=240)
    region = models.CharField(
        help_text="State or Province of the campus (Abbreviation preffered)", max_length=100)
    telephone = models.CharField(
        help_text="Phone number of the campus", max_length=50, blank=True)
    zip_code = models.CharField(
        help_text="Zip or Postal Code of the campus", max_length=10, blank=True)

    lat = models.FloatField(blank=True, null=True)
    lon = models.FloatField(blank=True, null=True)
    point = models.PointField(blank=True, null=True)

    objects = models.GeoManager()

    def __str__(self):
        return "{0} \n {1}, {2}".format(self.street_address, self.locality, self.region)

    def save(self, *args, **kwargs):
        if self.point is None:
            from haystack.utils.geo import Point
            if self.lon is not None and self.lat is not None:
                self.point = Point(self.lon, self.lat)
            elif self.full_address != "":
                try:
                    from geopy.geocoders import GoogleV3
                    geolocator = GoogleV3()
                    try:
                        lat, lon = geolocator.geocode(self.full_address)[1]
                        self.lat = lat
                        self.lon = lon
                        self.point = Point(lon, lat)
                    except IndexError:
                        pass
                except Exception:
                    pass

            # TODO: else with the street address and geo encoder via google or something
        super(CampusLocation, self).save(*args, **kwargs)

    @property
    def full_address(self):
        ctx = {
            'street_address': self.street_address,
            'additional_address': self.additional_address,
            'locality': self.locality,
            'region': self.region,
            'zip_code': self.zip_code,
        }
        full_address = """
        {street_address} {additional_address}, {locality}, {region}, {zip_code}
        """.format(**ctx)
        return full_address

apps/world/models.py
from django.contrib.gis.db import models


class WorldBorder(models.Model):
    # Regular Django fields corresponding to the attributes in the
    # world borders shapefile.
    name = models.CharField(max_length=50)
    area = models.IntegerField()
    pop2005 = models.IntegerField('Population 2005')
    fips = models.CharField('FIPS Code', max_length=2)
    iso2 = models.CharField('2 Digit ISO', max_length=2)
    iso3 = models.CharField('3 Digit ISO', max_length=3)
    un = models.IntegerField('United Nations Code')
    region = models.IntegerField('Region Code')
    subregion = models.IntegerField('Sub-Region Code')
    lon = models.FloatField()
    lat = models.FloatField()

    # GeoDjango-specific: a geometry field (MultiPolygonField), and
    # overriding the default manager with a GeoManager instance.
    mpoly = models.MultiPolygonField()
    objects = models.GeoManager()

    # Returns the string representation of the model.
    def __str__(self):              # __unicode__ on Python 2
        return self.name

apps/geovinci/views/front.py
from django.shortcuts import render


def index(request):
    ctx = {}
    template_name = "geovinci/front/index.html"
    return render(request, template_name, ctx)

apps/nearme/views.py
from django.shortcuts import render

# Create your views here.

apps/nearme/views/api.py
from django.shortcuts import render
from django.contrib.gis.geoip import GeoIP
from django.contrib.gis.geos import Point
from haystack.query import SearchQuerySet

from nearme.models import CampusLocation

def coarse(request):
    ctx = {}
    ctx['demo'] = "coarse"
    template_name = "nearme/front/index.html"

    ip_addr = request.META['REMOTE_ADDR']
    print("Actual IP: {0}".format(ip_addr))
    # Faked IP based on Zaniac Sugar House
    FAKED_IP = "50.77.46.89"
    ip_addr = FAKED_IP

    ctx['ip'] = ip_addr
    g = GeoIP()
    ctx['city'] = g.city(ip_addr)

    return render(request, template_name, ctx)


def fine(request):
    ctx = {}
    ctx['demo'] = "fine"
    template_name = "nearme/front/index.html"

    return render(request, template_name, ctx)


def campuses(request):
    ctx = {}
    ctx['marker'] = {}
    ctx['demo'] = "campuses"
    template_name = "nearme/front/campuses.html"

    print(request.GET)
    lat, lng = request.GET.get('lat', None), request.GET.get('lng', None)
    if lat is not None and lng is not None:
        ctx['marker']['lat'], ctx['marker']['lng'] = lat, lng

    query_method = request.GET.get('qmethod', 'geodjango')
    ctx['qmethod'] = query_method

    if lat is not None and lng is not None:
        qmethod = query_method.lower()
        ref_location = Point(float(lng), float(lat))  # because x, y
        if qmethod == "geodjango":
            campus_locations = CampusLocation.objects.all().distance(ref_location).order_by('distance')
            ctx['campus_locations'] = campus_locations
        elif qmethod == "haystack":
            ctx['campus_locations'] = []
            campus_locations = SearchQuerySet().distance('location', ref_location).order_by('distance')
            print(campus_locations)
            for s in campus_locations:
                ctx['campus_locations'].append({
                    'lat': s.object.lat,
                    'lon': s.object.lon,
                    'full_address': s.object.full_address,
                    'id': s.object.id,
                    'distance': s.distance
                    })


    return render(request, template_name, ctx)

apps/nearme/views/front.py
from django.shortcuts import render


def index(request):
    ctx = {}
    ctx['demo'] = "index"
    template_name = "nearme/front/index.html"
    return render(request, template_name, ctx)

apps/geovinci/templates/_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>GeoDjango Demo</title>
    <link rel="icon" href="{{ STATIC_URL }}img/globeicon.png" type="image/x-icon" />

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    {# {% leaflet_js %} #}
    {# {% leaflet_css %} #}
    <script src='https://api.mapbox.com/mapbox.js/v2.2.1/mapbox.js'></script>
    <link href='https://api.mapbox.com/mapbox.js/v2.2.1/mapbox.css' rel='stylesheet' />
    <style>
      /*body { margin:0; padding:0; }*/
      #map { 
        width: 100%;
        height: 575px;
      }
    </style>
  </head>
  <body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mainnav" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">
          <img alt="Brand" src="{{ STATIC_URL }}img/globeicon.png" width="20" height="20">
        </a>
      </div>
      <div class="collapse navbar-collapse" id="mainnav">
        <ul class="nav navbar-nav">
          {% block navcontent %}
          {% endblock %}
        </ul>
      </div>
    </div>
  </nav>
  <div class="container-fluid">
    {% block content %}
    {% endblock %}
  </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    {# Mapbox access token #}
    <script type="text/javascript">
      var mapbox_access_token = "pk.eyJ1IjoiZm9lbml4IiwiYSI6Ijk1MzJiODk1ODMzNTQwZTcwMmYzMGM5NjBjODQ3YTZjIn0.0V8EPoeyNLXtJSQ1XOi7NA";
    </script>
    {% block js %}
    {% endblock %}
  </body>
</html>

apps/geovinci/templates/geovinci/front/index.html
{% extends "_base.html" %}
{% block navcontent %}
  <li><a href="{% url 'nearme:index' %}">Near Me Demos</a></li>
{% endblock %}
{% block content %}

<div class="row">
  <div class="span-col-12">
    <div id="map"></div>
  </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
    L.mapbox.accessToken = mapbox_access_token;
    // Replace 'mapbox.streets' with your map id.
    var mapboxTiles = L.tileLayer('https://api.mapbox.com/v4/mapbox.comic/{z}/{x}/{y}.png?access_token=' + L.mapbox.accessToken, {
      attribution: '<a href="http://www.mapbox.com/about/maps/" target="_blank">Terms &amp; Feedback</a>'
    });

    var map = L.map('map')
        .addLayer(mapboxTiles)
        .setView([40.7255777, -111.8611107], 15);
</script>
{% endblock %}

apps/nearme/templates/nearme/front/campuses.html
{% extends "nearme/front/index.html" %}

{% block content %}

<div class="col-md-10">
  <div id="map" class="well">
  </div>
</div>

<div class="col-md-2">
  <h2>Campuses</h2>
  <p><b>Current Method:</b> {{ qmethod }}</p>
  <form action="." method="GET">
    <div class="btn-group">
      <button type="submit" name="qmethod" value="GeoDjango" class="btn btn-info">GeoDjango</button>
      <button type="submit" name="qmethod" value="Haystack" class="btn btn-success">Haystack</button>
    </div>
    <input type="hidden" name="lat" value="{{ marker.lat }}" />
    <input type="hidden" name="lng" value="{{ marker.lng }}" />
  </form>
  <p><code>{{ marker.lat }}, {{ marker.lng }}</code></p>

  {% for campus in campus_locations %}
  <div class="well">
    <p><code>
      {{ campus.lat }}, {{ campus.lon }}
    </code></p>
    <p>
      {{ campus.full_address }}
    </p>
    <p><b>Distance:</b> {{ campus.distance.mi|floatformat:"1" }} miles</p>
  </div>
  {% endfor %}
</div>
<div class="col-md-12">
  <div id="info" class="">
  </div>
</div>

{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ STATIC_URL }}nearme/js/geoFindMe.js"></script>
<script type="text/javascript">
    L.mapbox.accessToken = mapbox_access_token;
  // Replace 'mapbox.streets' with your map id.
  // var mapboxTiles = L.tileLayer('https://api.mapbox.com/v4/foenix.05b98193/{z}/{x}/{y}.png?access_token=' + L.mapbox.accessToken, {
  // var mapboxTiles = L.tileLayer('https://api.mapbox.com/v4/mapbox.dark/{z}/{x}/{y}.png?access_token=' + L.mapbox.accessToken, {
  var mapboxTiles = L.tileLayer('https://api.mapbox.com/v4/mapbox.comic/{z}/{x}/{y}.png?access_token=' + L.mapbox.accessToken, {
    attribution: '<a href="http://www.mapbox.com/about/maps/" target="_blank">Terms &amp; Feedback</a>'
  });

  var map = L.map('map')
      .addLayer(mapboxTiles);
  {% if marker.lat and marker.lng %}
  var latitude = {{ marker.lat }};
  var longitude = {{ marker.lng }};
  map.setView([{{ marker.lat }}, {{ marker.lng }}], 12);
  var marker = L.marker([latitude, longitude], {
  icon: L.mapbox.marker.icon({
    'marker-color': '#31708f'
    }),
  draggable: true
  });
  console.debug(latitude, longitude);

  marker.on('dragend', function(e){
    console.debug(marker.getLatLng());
    latlng = marker.getLatLng();
    window.location.href = window.location.origin + window.location.pathname + "?lat=" + latlng.lat + "&lng=" + latlng.lng;
  });
  marker.addTo(map);

  {% if campus_locations %}
  {# dirty js!  Don't do this unless you're in a hackathon #}
    {% for campus in campus_locations %}
      var marker_{{ campus.id }} = L.marker([{{ campus.lat }}, {{ campus.lon }}], {
        icon: L.mapbox.marker.icon({
          'marker-color': '#f86767'
          }),
        });
      marker_{{ campus.id }}.addTo(map)
        .bindPopup(
          "{{ campus.full_address|escapejs }}"
          );

    {% endfor %}
  {% endif %}

  {% else %}
  geoFindMe(map);
  map.setView([40.7563925, -111.8985922], 13);
  {% endif %}
</script>
{% endblock %}

apps/nearme/templates/nearme/front/index.html
{% extends "_base.html" %}

{% block navcontent %}
  <li class="{% if demo == 'index' %}active{% endif %}"><a href="{% url 'nearme:index' %}">Near Me Demo</a></li>
  <li class="{% if demo == 'coarse' %}active{% endif %}"><a href="{% url 'nearme:coarse' %}">Coarse</a></li>
  <li class="{% if demo == 'fine' %}active{% endif %}"><a href="{% url 'nearme:fine' %}">Fine</a></li>
  <li class="{% if demo == 'campuses' %}active{% endif %}"><a href="{% url 'nearme:campuses' %}">Campuses</a></li>
{% endblock %}

{% block content %}

<div class="col-md-10">
  <div id="map">
  </div>
</div>

<div class="col-md-2">
  <div id="info" class="well">
    <p>{{ city.city }}</p>
    <p><code>{{ city.latitude }}, {{ city.longitude }}</code></p>
  </div>
</div>

{% endblock %}

{% block js %}
{% if demo == "fine" %}
<script type="text/javascript" src="{{ STATIC_URL }}nearme/js/geoFindMe.js"></script>
{% endif %}
<script type="text/javascript">
    L.mapbox.accessToken = mapbox_access_token;
    // Replace 'mapbox.streets' with your map id.
    var mapboxTiles = L.tileLayer('https://api.mapbox.com/v4/mapbox.comic/{z}/{x}/{y}.png?access_token=' + L.mapbox.accessToken, {
      attribution: '<a href="http://www.mapbox.com/about/maps/" target="_blank">Terms &amp; Feedback</a>'
    });

    var map = L.map('map')
        .addLayer(mapboxTiles);
        
{% if demo == "coarse" %}
    map.setView([{{ city.latitude }}, {{ city.longitude }}], 11);
    
    var marker = L.marker([{{ city.latitude }}, {{ city.longitude }}], {
    icon: L.mapbox.marker.icon({
      'marker-color': '#f86767'
      })
    });

    marker.addTo(map);
{% elif demo == "fine" %}
    geoFindMe(map);
{% else %}
    map.setView([40.7563925, -111.8985922], 11);
{% endif %}
</script>
{% endblock %}